### ISSUE TITLE
Create BIDS skeleton according to BEP

### ISSUE THREAD

**Issue by Brainhack-NY** [emilyolafson/eyetrack-ANT#3]
See [BEP proposal for pupil data](https://docs.google.com/document/d/1eggzTCzSHG3AEKhtnEDbcdk-2avXN6I94X8aUPEBVsw/edit)

**Comment by axiezai** [comment]
Me do dis :)

**Comment by axiezai** [comment]
See #4

**Comment by Brainhack-NY** [comment]
Still need to:
 - Fill in `.json` files and participant list
 - Open the data somehow and convert to `.csv/.tsv` files

Oops used wrong github account, this is bobby btw :P
